"""Upgrade Todos model

Revision ID: 105cf96bbbfc
Revises: 5752954ebf8d
Create Date: 2021-08-15 13:23:03.988253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "105cf96bbbfc"
down_revision = "5752954ebf8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column(
            "resolved_status", sa.Boolean(), nullable=True, comment="Resolved status"
        ),
    )
    op.drop_index("ix_users_email", table_name="users_router")
    op.drop_index("ix_users_id", table_name="users_router")
    op.drop_index("ix_users_username", table_name="users_router")
    op.create_index(
        op.f("ix_users_router_email"), "users_router", ["email"], unique=True
    )
    op.create_index(op.f("ix_users_router_id"), "users_router", ["id"], unique=True)
    op.create_index(
        op.f("ix_users_router_username"), "users_router", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_router_username"), table_name="users_router")
    op.drop_index(op.f("ix_users_router_id"), table_name="users_router")
    op.drop_index(op.f("ix_users_router_email"), table_name="users_router")
    op.create_index("ix_users_username", "users_router", ["username"], unique=False)
    op.create_index("ix_users_id", "users_router", ["id"], unique=False)
    op.create_index("ix_users_email", "users_router", ["email"], unique=False)
    op.drop_column("todos", "resolved_status")
    # ### end Alembic commands ###
