"""Init

Revision ID: 5752954ebf8d
Revises: 
Create Date: 2021-08-12 21:46:28.711471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5752954ebf8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='Username'),
    sa.Column('registered_datetime', sa.DateTime(), nullable=True, comment='Registration date and time'),
    sa.Column('password', sa.String(length=256), nullable=True, comment='User password'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='User email'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Is a SuperUser?'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='Title of Todos'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='Description of Todos'),
    sa.Column('created_date', sa.DateTime(), nullable=True, comment='Date when created'),
    sa.Column('resolved_date', sa.DateTime(), nullable=True, comment='Date when resolved'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
